import { spawnSync } from 'node:child_process';

const args = [
  'harness/status.mjs', 'set', 'game.play',
  '--round', '3', '--verdict', 'REJECT', '--score', '46', '--owner', 'critic-dig-3',
  '--summary',
  "DIG round 3: the corrugation fix genuinely worked (teal core measured flat, ~130-146 luminance over 150px on two frames, replacing round 2's measured 30<->152 oscillation) and crater proportion, dark frames and debris shapes all confirm improved -- but round 2's hypothesis that this ONE change would also fix identification was wrong: a flat bright teal pool with two rounded debris chunks resting in it now reads, confidently, as an aerial photo of a lagoon with islands in 3 of 4 no-context crops, which is a worse failure mode than round 2's three-mutually-disagreeing guesses. White shell still lacks real cross-sectional depth. The vertical seam's claim of real batten geometry does not hold (intact wall beside the hole is a perfectly smooth gradient, zero batten texture) but the residual defect is now small, confined to roughly the top 60px of white-shell crack linework, not the full cavity height.",
  '--clear-hates',
  '--hates',
  "IDENTIFICATION GATE STILL FAILS, AND NOW FAILS CONVERGENTLY INSTEAD OF AMBIGUOUSLY. Four independent no-context crops taken this round (two from thick-12, one each from thick-14 and thick-13, at different zoom levels): three of the four drew the same unprompted first read -- 'aerial photo of a lagoon or tide pool with small rocky islands' -- not a hole in a wall exposing structural material. Only the most oblique crop (thick-3, viewed edge-on as a thin vertical strip) read correctly. This is a regression in KIND from round 2's three-different-wrong-guesses: before, the material was ambiguous; now a stranger would answer confidently and be confidently wrong. Round 2's bet that stripping the corrugation would also fix identification did not pay off -- a perfectly flat, bright, unbroken cyan surface viewed close to face-on is exactly what reads as still water, and it did.",
  '--hates',
  "THE NEW 'core' DEBRIS CHUNKS ARE THE SPECIFIC CUE THAT SELLS THE LAGOON MISREAD. The pale rounded blob and the dark speckled island shape sitting in the middle of the flat teal pool sit exactly like partially-submerged rocks or islets in a body of water -- they are the single strongest driver of the wrong identification, more than the flat color alone. Fix target for round 4: either recess them so they read as part of the cut face rather than floating on the surface, or drop them from the flat-teal frames entirely.",
  '--hates',
  "WHITE SHELL STILL SHORT OF A READABLE CROSS-SECTION. Close-up crop of the white-to-teal boundary (thick-12) shows a modest dark contact-shadow fringe at the join -- real, but small, improvement over paper-thin. It does not produce the readable material band dig-barrier-stages.webp and dig-iso-cutaway.jpg both show in cross-section. Checked all three grazing frames in this evidence set (thick-9/10/11, nominally 18/15/11.7 degrees) hoping an oblique angle would reveal a visible profile edge -- none of the three actually frames the wall edge-on enough to show one; they read close to head-on. The code-side 0.900->0.615 number given for this round does not translate into a visible slab edge in any frame checked.",
  '--hates',
  "VERTICAL SEAM'S CLAIM OF REAL GEOMETRY DOES NOT HOLD UP, THOUGH THE DEFECT ITSELF IS NOW MINOR. Measured with a center-vs-flank luminance probe at x=690 on both thick-8 and thick-13: a real, consistent one-directional dip (33 to 90 luminance units) exists ONLY in the top ~60px, inside the white shell's own crack linework -- consistent with being one more crack stroke, not a bug. Below that, inside the teal core, the same probe flips sign about as often as not (noise, not a seam), so round 2's full-cavity-height claim is already gone regardless of the geometry story. The real test of the geometry claim: a column-average scan of the INTACT wall immediately beside the hole (thick-13, x=250-580, y=100-400) is a perfectly smooth lighting gradient, 36 up to 78, with zero periodic structure -- no boiserie, no battens, nowhere on the undamaged wall. If a 25mm batten genuinely ran through this wall it should show either side of the hole; it does not. Treat this as a small residual decal/crack-linework artifact, not out-of-scope geometry.",
  '--hates',
  "MINOR: rendered teal runs paler than the reference teal. Sampled reference (dig-ballroom-breach-early.webp) at several points in its cyan field: roughly (40-50, 120-130, 125-130). Sampled render teal core (thick-12): roughly (64-68, 164-169, 164-169). Same hue family, R well below G/B in both, but the render sits noticeably lighter/less saturated. Lowest priority on this list.",
  '--hates',
  "[preserved from r16, not re-verified this round] ONE SECOND OF TRIGGER SORTS ALL THREE CLOSED STATES, SO THE CONCEALMENT IS COSMETIC. Measured in play (pc8-tap.mjs, the gallery, real keys, real trigger, seeds s4 and s43, all seven connectors). After 1.0 s of held trigger the sort is already legible; the search (about fourteen taps) is cheaper than the payoff (15-25 s siege).",
  '--hates',
  "[preserved from r16, not re-verified this round] THE GAMBLE JOHN DESCRIBED CANNOT HAPPEN IN THIS BUILD. EXIT_DEFS (4900/4340/3000 hp) is used by exactly one connector per run; the other twenty-one are 255 hp (1.25 s) or non-damageable, so a 15-25 s siege is itself an unambiguous exit signal.",
  '--hates',
  "[preserved from r16, not re-verified this round] THE SIEGE HAS NO PLAYER-FACING FEEDBACK. Seed s43, 26.6 s held trigger: hunter.threat sat around 1.5% of its range the whole siege, and the game has zero audio hits anywhere in src/.",
  '--hates',
  "[preserved from r16, not re-verified this round] THE BEAMS LOCK DELETES ALL THREE DESIGN PILLARS ON ABOUT A THIRD OF SEEDS. s37 beams: exterior.census() reads exposed:true at t=0 before the player moves -- the answer is free from frame one on that lock.",
  '--hates',
  "[preserved from r16, not re-verified this round] THE SIEGE DANGER IS ENTIRELY POSITIONAL AND HAS NO MIDDLE. s43 gallery: hunter never exceeded SEARCH in 26.6 s. s0 ballroom: DOWNED eleven seconds in, found by sight at 6.4 m, not by breach noise.",
  '--hates',
  "[preserved from r16, not re-verified this round] THE DAYLIGHT SEAM IS DRAWN ON INTERIOR PARTITIONS -- A PHYSICAL LIE, NOT AN UNRELIABLE HINT. 44.5% of all connectors wear the day-lit perimeter glow regardless of what's behind them, including interior-to-interior walls.",
  '--wins',
  "CORRUGATION ON THE TEAL CORE IS GENUINELY GONE -- THE #1 COMPLAINT, VERIFIED, NOT JUST CLAIMED. Repeated round 2's exact measurement (thick-12, y=220, x=720-960): this round reads flat, 130 to 146 luminance drifting smoothly, versus round 2's measured 30<->152 oscillation every 20-40px. Cross-checked a second frame (thick-15) at the same y: same flat, non-periodic result over a 100-150px stretch. This is a real fix, not a relocation.",
  '--wins',
  "CRATER PROPORTION NOW READS AS A HOLE IN A WALL, NOT A WALL OF HOLE. Every full-context frame checked (thick-8, thick-13, thick-16) shows ample plain wall margin around the opening. Matches the claimed radius reduction.",
  '--wins',
  "DARK-FRAME COMPLAINT LARGELY RESOLVED. thick-6 (previously 'roughly half black') is now clearly legible -- cyan ring, white shell and debris pile all readable even with the foreground wall in shadow; that shadow reads as intentional lighting (viewed from the far side of the breach), not failure. No frame in this evidence set is unjudgeable.",
  '--wins',
  "DEBRIS SHAPES CLEANED UP. Close crop of the main pile (thick-12) shows convincing angular low-poly chunks in white/cream and new teal tones, comparable scale to dig-gallery-sledge-crew.webp; did not find the paper-ribbon or flat-shard shapes round 2 flagged.",
  '--wins',
  "[preserved from r16, not re-verified this round] THE SIEGE IS REAL, THE WIN IS REACHABLE. Seed s4: ESCAPED at t=28.99s, four of four limbs. Seed s43: exit opened after a legible 26.6s stage progression.",
  '--wins',
  "[preserved from r16, not re-verified this round] THE BEAM REVEAL LANDS, AND IT IS THE BEST FRAME IN THE GAME. s43: blocksSight false at t=17.78s with 2976/3000 hp still to chew -- a genuine change of state, dark lath to daylight and yard.",
  '--wins',
  "[preserved from r16, not re-verified this round] THE DRESSING IS HONEST. Could not identify the live exit visually across four seeds; builder figures on DRESS_P reproduce exactly offline.",
  '--wins',
  "[preserved from r16, not re-verified this round] JOHN 5-SECOND FREEZES ARE GONE. Two 5-min sessions at quality=medium, p99 8.2-8.8ms, compilation warm-up confirmed working.",
];

const res = spawnSync(process.execPath, args, { stdio: 'inherit', cwd: 'C:/Users/John/Documents/Run Robot Run/web-prototype' });
process.exit(res.status ?? 1);
