/** _rc_gap — the gate plays room.js; the show plays session.js. What differs? Probe. */
import { createRoom } from '../../src/party/room.js';
import { play } from './_rc_inv.mjs';
import { awards, reunion } from '../../src/party/reunion.js';
const state={},events={};
const r = createRoom({count:8,castSeed:11*41,worldSeed:11,send:(i,f)=>{(state[i]=state[i]||[]).push(f)},emit:(i,e)=>{(events[i]=events[i]||[]).push(e)}});
r.start(); r.playEpisode({hunterRoom:'cellar'});
const living=r.state.players.filter(p=>p.alive).map(p=>p.id);
r.playEpisode({hunterRoom:'gallery',takeRunner:true,nominations:[{nominator:living[1],target:living[3]}],votes:Object.fromEntries(living.map(i=>[i,living[3]]))});
r.playMatch({hunterRoom:'hall'});
const roomTypes = new Set(r.log.all().map(e=>e.type));
const s = play({castSeed:100,worldSeed:7});
const sessTypes = new Set(s.log.map(e=>e.type));
console.log('=== what the GATE (room.js) sees but the SHOW (session.js) never writes ===');
console.log('  ', [...roomTypes].filter(t=>!sessTypes.has(t)).sort().join(', ') || '(none)');
console.log('=== what the SHOW writes but the GATE never sees ===');
console.log('  ', [...sessTypes].filter(t=>!roomTypes.has(t)).sort().join(', ') || '(none)');
const rs = r.log.all().filter(e=>e.vis==='SEALED');
console.log('\ngate\'s sealed inventory:', [...new Set(rs.map(e=>e.type))].sort().join(', '));
console.log('show\'s sealed inventory:', [...new Set(s.log.filter(e=>e.vis==='SEALED').map(e=>e.type))].sort().join(', '));
console.log('\ngate log length', r.log.all().length, '· show log length', s.log.length);
