/**
 * The piece registry. This IS the work breakdown: every entry is one thing that can be
 * built, screenshotted and judged entirely on its own. A critic is handed exactly one
 * `id` and never sees the rest of the game.
 *
 * `bar` is what the critic compares against — a Dev Art file, a real game, or a photo.
 * `crop` hints at the region a blind identification test should cut from.
 */

export const VIEWS = [
  // ---------------- materials: the base of everything ----------------
  { id: 'mat.marble',     group: 'material', title: 'Marble floor + veining',
    bar: 'Dev Art 1785319916301 floor; Hitman 3 Paris ballroom marble',
    module: () => import('./views/mat-marble.js') },
  { id: 'mat.walnut',     group: 'material', title: 'Walnut panelling + gilding',
    bar: 'Dev Art 1785319916301 walls; BF1 Ballroom Blitz panelling',
    module: () => import('./views/mat-walnut.js') },
  { id: 'mat.wallpaper',  group: 'material', title: 'Damask wallpaper',
    bar: 'Hitman 3 Paris salon silk damask',
    module: () => import('./views/mat-wallpaper.js') },
  { id: 'mat.plaster',    group: 'material', title: 'Lime plaster + horsehair',
    bar: 'lath-and-plaster demolition photographs',
    module: () => import('./views/mat-plaster.js') },
  { id: 'mat.lath',       group: 'material', title: 'Split timber lath',
    bar: 'Dev Art 1785320177684; lath demolition photographs',
    module: () => import('./views/mat-lath.js') },
  { id: 'mat.robot',      group: 'material', title: 'Robot shell / chrome / mint',
    bar: 'Dev Art 1785277053522 turnaround',
    module: () => import('./views/mat-robot.js') },
  { id: 'mat.brass',      group: 'material', title: 'Brass, gilt bronze, glass',
    bar: 'Dev Art gadget limbs; Hitman Paris chandelier',
    module: () => import('./views/mat-brass.js') },

  // ---------------- wall destruction: one view per stage ----------------
  { id: 'wall.0.paper',   group: 'wall', title: 'Stage 0 — wallpaper intact',
    bar: 'Hitman Paris silk wall', crop: 'flat wall, no floor, no ceiling',
    module: () => import('./views/wall-stage.js'), args: { stage: 0 } },
  { id: 'wall.1.plaster', group: 'wall', title: 'Stage 1 — plaster exposed',
    bar: 'demolition photo: paper stripped, bare lime plaster', crop: 'break edge only',
    module: () => import('./views/wall-stage.js'), args: { stage: 1 } },
  { id: 'wall.2.lath',    group: 'wall', title: 'Stage 2 — lath exposed',
    bar: 'Dev Art 1785320177684; demolition photo', crop: 'lath field only',
    module: () => import('./views/wall-stage.js'), args: { stage: 2 } },
  { id: 'wall.3.beam',    group: 'wall', title: 'Stage 3 — studs/beams only',
    bar: 'demolition photo: bare framing', crop: 'framing only',
    module: () => import('./views/wall-stage.js'), args: { stage: 3 } },
  { id: 'wall.4.open',    group: 'wall', title: 'Stage 4 — open air',
    bar: 'ragged opening, torn edges read as broken not cut', crop: 'opening edge',
    module: () => import('./views/wall-stage.js'), args: { stage: 4 } },
  { id: 'wall.transition', group: 'wall', title: 'Collapse — debris + dust burst',
    bar: 'BF1 wall collapse; real demolition dust',
    module: () => import('./views/wall-transition.js') },
  { id: 'wall.sheet',     group: 'wall', title: 'All five stages side by side',
    bar: 'each stage must be identifiable with no context',
    module: () => import('./views/wall-sheet.js') },

  // ---------------- characters ----------------
  { id: 'char.turnaround', group: 'char', title: 'UNIT-4H turnaround (4 views)',
    bar: 'Dev Art 1785277053522 — exact match',
    module: () => import('./views/char-turnaround.js') },
  { id: 'char.detail',     group: 'char', title: 'UNIT-4H head / shoulder / pelvis detail',
    bar: 'Dev Art 1785277053522 + 1785301780641',
    module: () => import('./views/char-detail.js') },
  { id: 'char.poses',      group: 'char', title: 'UNIT-4H reference poses',
    bar: 'Dev Art 1785301551166 / 1785301780641 / 1785308800211 / 1785309310525',
    module: () => import('./views/char-poses.js') },
  { id: 'char.locomotion', group: 'char', title: 'Run / walk / turn cycle',
    bar: 'weight and follow-through of AAA locomotion',
    module: () => import('./views/char-locomotion.js') },

  { id: 'hunter.1', group: 'hunter', title: 'Hunter stage 1',
    bar: 'Dev Art 1785300149293 BASELINE row',
    module: () => import('./views/hunter-stage.js'), args: { stage: 1 } },
  { id: 'hunter.2', group: 'hunter', title: 'Hunter stage 2',
    bar: 'Dev Art 1785300149293 STAGE 2 row — empty shoulder socket, hunch',
    module: () => import('./views/hunter-stage.js'), args: { stage: 2 } },
  { id: 'hunter.3', group: 'hunter', title: 'Hunter stage 3',
    bar: 'Dev Art 1785288883855 + STAGE 3 row — 6 arms, 2 heads, rider',
    module: () => import('./views/hunter-stage.js'), args: { stage: 3 } },
  { id: 'char.lineup', group: 'char', title: 'Every player robot we have built, one ground line',
    bar: 'the three must be tellable apart cold; ?names=1 labels them, ?all=1 adds the variants',
    crop: 'full row, feet to head',
    module: () => import('./views/char-lineup.js') },
  { id: 'mesh.compare', group: 'char', title: 'Generated mesh vs procedural player',
    bar: 'Dev Art 1785300149293 BASELINE row (the source of the generation inputs)',
    module: () => import('./views/mesh-compare.js') },
  { id: 'mesh.animated', group: 'char', title: 'Generated + auto-rigged, skinned and animated',
    bar: 'Dev Art 1785300149293 BASELINE row',
    module: () => import('./views/mesh-animated.js') },
  { id: 'mesh.rigged', group: 'char', title: 'Generated shell mounted on the rig',
    bar: 'Does the generated geometry pose with the skeleton?',
    module: () => import('./views/mesh-rigged.js') },
  { id: 'hunter.sheet', group: 'hunter', title: 'Hunter progression sheet',
    bar: 'Dev Art 1785300149293 — full sheet, same framing',
    module: () => import('./views/hunter-sheet.js') },
  { id: 'hunter.absorb', group: 'hunter', title: 'Absorb + grow transition',
    bar: 'must read as the hunter taking the part onto itself',
    module: () => import('./views/hunter-absorb.js') },
  { id: 'hunter.mesh', group: 'hunter', title: 'Generated hunter ramp, beside the generated player',
    bar: 'must read as the SAME CHASSIS as the player in game.play, corrupted',
    module: () => import('./views/hunter-mesh.js') },

  // ---------------- limbs and gadgets ----------------
  { id: 'limb.detach',  group: 'limb', title: 'Limb detach / reattach',
    bar: 'Dev Art 1785319916301 — leg held as a club',
    module: () => import('./views/limb-detach.js') },
  { id: 'gadget.nailgun', group: 'gadget', title: 'Nail gun limb',
    bar: 'Dev Art 1785313925351 — exact match',
    module: () => import('./views/gadget.js'), args: { gadget: 'nailgun' } },
  { id: 'gadget.oil',     group: 'gadget', title: 'Oil lobber limb',
    bar: 'Dev Art 1785315723570 — exact match',
    module: () => import('./views/gadget.js'), args: { gadget: 'oil' } },
  { id: 'gadget.skates',  group: 'gadget', title: 'Rocket skates',
    bar: 'Dev Art 1785314396477 — exact match',
    module: () => import('./views/gadget.js'), args: { gadget: 'skates' } },
  { id: 'gadget.grapple', group: 'gadget', title: 'Grappling hook limb',
    bar: 'Dev Art 1785320715285 — exact match',
    module: () => import('./views/gadget.js'), args: { gadget: 'grapple' } },
  { id: 'gadget.ball',    group: 'gadget', title: 'Bouncy ball gun limb',
    bar: 'Dev Art 1785320614586 — exact match',
    module: () => import('./views/gadget.js'), args: { gadget: 'ball' } },
  { id: 'gadget.sheet',   group: 'gadget', title: 'All five gadget limbs',
    bar: 'all five Dev Art gadget shots',
    module: () => import('./views/gadget-sheet.js') },

  // ---------------- the estate ----------------
  { id: 'room.ballroom',  group: 'room', title: 'Grand ballroom',
    bar: 'BF1 Ballroom Blitz; Hitman 3 Paris atrium',
    module: () => import('./views/room-ballroom.js') },
  { id: 'room.study',     group: 'room', title: 'Panelled study',
    bar: 'Dev Art 1785319916301 — same room, matched',
    module: () => import('./views/room-study.js') },
  { id: 'room.gallery',   group: 'room', title: 'Portrait gallery + stair',
    bar: 'Hitman 3 Paris gallery',
    module: () => import('./views/room-gallery.js') },
  { id: 'prop.chandelier', group: 'room', title: 'Chandelier (lit, destructible)',
    bar: 'Hitman Paris chandelier; BF1 ballroom',
    module: () => import('./views/prop-chandelier.js') },
  { id: 'light.dark',    group: 'light', title: 'Alien: Isolation darkness',
    bar: 'Alien: Isolation — dark you cannot see into',
    module: () => import('./views/light-dark.js') },
  { id: 'light.shaft',   group: 'light', title: 'Stained-glass volumetric shaft',
    bar: 'Dev Art 1785319916301 / 1785320177684 light shaft',
    module: () => import('./views/light-shaft.js') },

  // ---------------- the game ----------------
  { id: 'game.play',     group: 'game', title: 'Playable slice',
    bar: 'all of the above, together, at 60fps',
    module: () => import('./views/game.js') },
  { id: 'furn.smash',    group: 'game', title: 'Meshy furniture smash lab',
    bar: 'Teardown sledge feel — docs/design/teardown-reference.md + refs/teardown/',
    module: () => import('./views/furn-smash.js') },
];

export const VIEW_BY_ID = new Map(VIEWS.map((v) => [v.id, v]));
export const GROUPS = [...new Set(VIEWS.map((v) => v.group))];
