import { chromium } from 'playwright';
import fs from 'node:fs';
const [src, out, x, y, w, h] = process.argv.slice(2);
const b = fs.readFileSync(src).toString('base64');
const br = await chromium.launch();
const pg = await br.newPage();
const png = await pg.evaluate(async ([b64, X, Y, W, H]) => {
  const bin = atob(b64); const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  const bmp = await createImageBitmap(new Blob([arr], { type: 'image/png' }));
  const c = new OffscreenCanvas(W, H);
  c.getContext('2d').drawImage(bmp, X, Y, W, H, 0, 0, W, H);
  const blob = await c.convertToBlob({ type: 'image/png' });
  const buf = new Uint8Array(await blob.arrayBuffer());
  let s = ''; for (const v of buf) s += String.fromCharCode(v);
  return btoa(s);
}, [b, +x, +y, +w, +h]);
fs.writeFileSync(out, Buffer.from(png, 'base64'));
await br.close();
console.log('wrote', out);
